from __future__ import annotations

import json
import urllib.parse
from pathlib import Path
from typing import Any, Dict, Iterable, List

from .gp_config import Config
from .gp_net import http_get_json

DISPLAYCATALOG_URL = "https://displaycatalog.mp.microsoft.com/v7.0/products"


def build_url(base: str, params: Dict[str, str]) -> str:
    return base + "?" + urllib.parse.urlencode(params)


def chunked(seq: List[str], size: int) -> Iterable[List[str]]:
    for i in range(0, len(seq), size):
        yield seq[i:i + size]


def ensure_dirs(out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "_meta").mkdir(exist_ok=True)
    (out_dir / "_lists").mkdir(exist_ok=True)
    return out_dir / "_meta"


def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False), encoding="utf-8")


def write_product(out_dir: Path, product: Dict[str, Any]) -> bool:
    pid = product.get("ProductId")
    if not isinstance(pid, str) or not pid:
        return False
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{pid}.json").write_text(json.dumps(product, indent=2, ensure_ascii=False), encoding="utf-8")
    return True


def fetch_products(cfg: Config, big_ids: List[str]) -> List[Dict[str, Any]]:
    url = build_url(
        DISPLAYCATALOG_URL,
        {"bigIds": ",".join(big_ids), "market": cfg.market, "languages": cfg.language},
    )
    payload = http_get_json(url, cfg.timeout_s)
    products = payload.get("Products", []) if isinstance(payload, dict) else []
    return products if isinstance(products, list) else []


def _load_language_cache_products(language_dir: Path) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    if not language_dir.exists():
        return out
    for p in sorted(language_dir.glob("*.json")):
        if not p.is_file():
            continue
        try:
            obj = json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            continue
        gameid = p.stem
        if isinstance(obj, dict) and isinstance(obj.get("ProductId"), str) and obj["ProductId"]:
            gameid = obj["ProductId"]
        out[gameid] = obj
    return out


def _load_language_cache_lists(language_dir: Path) -> Dict[str, Any]:
    out: Dict[str, Any] = {}
    lists_dir = language_dir / "_lists"
    if not lists_dir.exists():
        return out
    for p in sorted(lists_dir.glob("*.json")):
        if not p.is_file():
            continue
        try:
            obj = json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            continue
        out[p.stem] = obj
    return out


def _fix_protocol_relative_urls(node: Any) -> Any:
    if isinstance(node, str) and node.startswith("//"):
        return "https:" + node
    if isinstance(node, list):
        return [_fix_protocol_relative_urls(x) for x in node]
    if isinstance(node, dict):
        return {k: _fix_protocol_relative_urls(v) for k, v in node.items()}
    return node


def export_catalog_data_js(*, cache_root: Path, out_path: Path) -> Dict[str, int]:
    products: Dict[str, Dict[str, Any]] = {}
    lists: Dict[str, Dict[str, Any]] = {}
    counts: Dict[str, int] = {}

    for lang_code in ("EN", "UA"):
        lang_dir = cache_root / lang_code
        prod_map = _load_language_cache_products(lang_dir)
        list_map = _load_language_cache_lists(lang_dir)
        products[lang_code] = _fix_protocol_relative_urls(prod_map)
        lists[lang_code] = _fix_protocol_relative_urls(list_map)
        counts[lang_code] = len(prod_map)

    data = {"products": products, "lists": lists}
    js_obj = json.dumps(data, ensure_ascii=False, indent=2)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        "// Auto-generated by Gamepass Parser. Do not edit by hand.\n"
        "window.GAMEPASS_DATA = " + js_obj + ";\n",
        encoding="utf-8",
    )
    return counts
